const {test}=require('node:test'),assert=require('node:assert/strict')
const {load,fixture,time}=require('./instance-planning-harness.cjs')
const M='users/alice/careerInstances/ix',S=M+'/sharing/snapshot'
function setup(){const records=new Map(Object.entries(fixture())),reads=[],auth={currentUser:{uid:'alice'}};let version=0,hook=()=>{},failure=null
const api=load({doc:(_, ...p)=>p.join('/'),serverTimestamp:()=>time,getDocFromServer:async p=>{reads.push(p);if(failure)throw failure;return snap(p)},runTransaction:async(_,fn)=>{for(let n=0;n<8;n++){const start=version,w=[];const out=await fn({get:async p=>{reads.push(p);hook(p);return snap(p)},set:(p,d)=>w.push([p,d]),update:(p,d)=>w.push([p,{...records.get(p),...d}])});if(start!==version)continue;if(failure)throw failure;for(const [p,d]of w)records.set(p,d);version++;return out}throw Error('conflict')}},auth,{})
function snap(p){const d=structuredClone(records.get(p));return {exists:()=>!!d,data:()=>d}}
return {api,records,reads,auth,fail:e=>failure=e,change:(p,d)=>{records.set(p,{...records.get(p),...d});version++},hook:f=>hook=f,enable:(i='ix',v=2)=>api.setInstancePlanningSharing('alice',i,true,v),disable:()=>api.setInstancePlanningSharing('alice','ix',false),refresh:()=>api.refreshInstancePlanningSnapshot('alice','ix')}}
test('S3-F explicit enable schema/path and disable preserve other instance',async()=>{const h=setup();await h.enable();assert.equal(h.records.get(S).schemaVersion,3);assert.equal(h.records.get(S).consentEpoch,1);assert.equal(h.records.get(M).sharing.enabled,true);await h.enable('iy');await h.disable();assert.equal(h.records.get(M).sharing.epoch,2);assert.equal(h.records.get('users/alice/careerInstances/iy').sharing.enabled,true)})
test('S3-F migrated consent v1 never silently upgrades',async()=>{const h=setup();await h.enable('ix',1);assert.equal('pendingFinalCodes' in h.records.get(S),false);await h.refresh();assert.equal('pendingFinalCodes' in h.records.get(S),false);await assert.rejects(h.api.setInstancePlanningSharing('alice','ix',true))})
test('S3-F progress refresh current revision, no progress writes',async()=>{const h=setup();await h.enable();h.change(M+'/academic/progress',{schemaVersion:1,statusMap:{A:'Aprobada'},revision:4,updatedAt:time});await h.refresh();assert.equal(h.records.get(S).sourceProgressRevision,4);assert.deepEqual(h.records.get(S).approvedCodes,['A'])})
test('S3-F refresh cannot create consent',async()=>{const h=setup();await assert.rejects(h.refresh());await h.enable();await h.disable();await assert.rejects(h.refresh())})
for(const authority of ['legacy','frozen'])test('S3-F authority '+authority+' fails closed',async()=>{const h=setup();h.change('migrationUsers/alice',{authority});await assert.rejects(h.enable());assert.equal(h.records.has(S),false)})
test('S3-F selection never read; explicit own state',async()=>{const h=setup();Object.defineProperty(h.auth.currentUser,'activeCareerInstanceId',{get(){throw Error('selection')}});await h.enable();const r=await h.api.readInstancePlanningSharing('alice','ix');assert.equal(r.catalogId,'catalog');assert.ok(!h.reads.includes('users/alice'))})
test('S3-F foreign reader reads only snapshot, retains identity',async()=>{const h=setup();await h.enable();h.auth.currentUser={uid:'bob'};h.reads.length=0;const r=await h.api.readInstancePlanningSnapshot('bob','alice','ix','catalog');assert.equal(r.careerInstanceId,'ix');assert.deepEqual(h.reads,[S]);await assert.rejects(h.api.readInstancePlanningSnapshot('bob','alice','ix','other'))})
test('S3-F malformed snapshot rejected; errors never fallback',async()=>{const h=setup();await h.enable();h.change(S,{extra:true});await assert.rejects(h.api.readInstancePlanningSnapshot('alice','alice','ix','catalog'));h.fail(Object.assign(Error('denied'),{code:'permission-denied'}));await assert.rejects(h.api.readInstancePlanningSnapshot('alice','bob','ix','catalog'),{code:'permission-denied'})})
test('S3-F enable disable concurrent serialized epoch',async()=>{const h=setup();await Promise.all([h.enable(),h.disable()]);assert.equal(h.records.get(M).sharing.epoch,2)})
test('S3-F refresh concurrent disable cannot reactivate consent',async()=>{const h=setup();await h.enable();await Promise.allSettled([h.refresh(),h.disable()]);assert.equal(h.records.get(M).sharing.enabled,false)})
test('S3-F archive racing enable retries and rejects; restore needs consent',async()=>{const h=setup();let once=false;h.hook(p=>{if(p===M&&!once){once=true;h.change(M,{lifecycle:'archived',archivedAt:time})}});await assert.rejects(h.enable());h.hook(()=>{});h.change(M,{lifecycle:'active',archivedAt:null});assert.equal(h.records.get(M).sharing,undefined);await h.enable()})
test('S3-F session change rolls back',async()=>{const h=setup();h.hook(()=>h.auth.currentUser={uid:'alice'});await assert.rejects(h.enable());assert.equal(h.records.has(S),false)})
