const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const P='nativeplan000001x',stamp={seconds:1700000000,nanoseconds:0};
function setup(){
 const auth={currentUser:{uid:'alice'}},writes=[],records=new Map(),calls=[];let failAt=0,commitError=null,onCommit=()=>{};
 const source=['src/jointPlanLogic.js','src/services/jointPlans.js'].map(p=>fs.readFileSync(path.resolve(__dirname,'..',p),'utf8').replace(/^import .*\r?\n/gm,'').replace(/export /g,'')).join('\n');
 const api=new Function('auth','db','collection','doc','writeBatch','serverTimestamp','assertSocialCreationAvailable',source+';return {createJointCPlan,decodeJointCPlan,decodeJointCSlot,decodeJointCRef};')(auth,{},(_db,...p)=>p.join('/'),(base,...p)=>p.length?{path:p.join('/'),id:p.at(-1)}:{path:base+'/'+P,id:P},()=>{calls.push('batch');return {set(ref,data){if(failAt===writes.length+1)throw Error('set failed');writes.push({path:ref.path,data})},async commit(){calls.push('commit');onCommit();if(commitError)throw commitError;for(const w of writes)records.set(w.path,w.data)}}},()=>stamp,()=>calls.push('maintenance'));
 return {...api,auth,writes,records,calls,failSet:n=>failAt=n,failCommit:e=>commitError=e,onCommit:fn=>onCommit=fn};
}
test('S2-C T1 six writes in one commit',async()=>{const a=setup();assert.equal(await a.createJointCPlan('alice','i_alice','catalog'),P);assert.equal(a.writes.length,6);assert.deepEqual(a.calls,['maintenance','batch','commit']);assert.equal(a.records.size,6)});
test('S2-C T2 generated canonical native parent',async()=>{const a=setup();await a.createJointCPlan('alice','i_alice','catalog');const p=a.decodeJointCPlan(a.records.get('jointPlans/'+P));assert.equal(p.schemaVersion,3);assert.equal(p.origin,'native');assert.equal(p.ownerId,'alice');assert.equal(p.ownerInstanceId,'i_alice');assert.equal(p.catalogId,'catalog')});
test('S2-C T3 four decoded empty slots',async()=>{const a=setup();await a.createJointCPlan('alice','i_alice','catalog');for(const w of a.writes.filter(w=>w.path.includes('/slots/'))){const s=a.decodeJointCSlot(w.data);assert.equal(s.status,'empty');assert.equal(s.revision,0);assert.equal(s.uid,null)}});
test('S2-C T4 exact unique slot IDs',async()=>{const a=setup();await a.createJointCPlan('alice','i_alice','catalog');assert.deepEqual(a.writes.filter(w=>w.path.includes('/slots/')).map(w=>w.path),[1,2,3,4].map(n=>`jointPlans/${P}/slots/slot${n}`))});
test('S2-C T5 owner ref exact identity and timestamp',async()=>{const a=setup();await a.createJointCPlan('alice','i_alice','catalog');const r=a.records.get('users/alice/jointPlanRefs/'+P);assert.deepEqual(a.decodeJointCRef(P,r),{planId:P});assert.ok(a.writes.every(w=>(w.data.createdAt||w.data.updatedAt)===stamp))});
test('S2-C T6 no session means no writes',async()=>{const a=setup();a.auth.currentUser=null;await assert.rejects(a.createJointCPlan('alice','i_alice','catalog'));assert.equal(a.calls.length,0)});
test('S2-C T7 cannot spoof owner uid',async()=>{const a=setup();await assert.rejects(a.createJointCPlan('bob','i_bob','catalog'));assert.equal(a.writes.length,0)});
test('S2-C T8 invalid required data rejected before batch',async()=>{for(const [i,c] of [[null,'catalog'],['i_alice',null],['','catalog'],['i/alice','catalog'],['i_alice','../catalog']]){const a=setup();await assert.rejects(a.createJointCPlan('alice',i,c));assert.equal(a.writes.length,0);assert.ok(!a.calls.includes('batch'))}});
test('S2-C T9 set/commit failures never report success or fallback',async()=>{for(let n=1;n<=6;n++){const a=setup();a.failSet(n);await assert.rejects(a.createJointCPlan('alice','i_alice','catalog'));assert.equal(a.records.size,0);assert.ok(!a.calls.includes('commit'))}for(const code of ['permission-denied','unavailable']){const a=setup(),e=Object.assign(new Error(code),{code});a.failCommit(e);await assert.rejects(a.createJointCPlan('alice','i_alice','catalog'),x=>x===e);assert.equal(a.records.size,0);assert.equal(a.calls.filter(x=>x==='commit').length,1)}});
test('S2-C T10 session replacement during commit rejects result',async()=>{const a=setup();a.onCommit(()=>a.auth.currentUser={uid:'alice'});await assert.rejects(a.createJointCPlan('alice','i_alice','catalog'),/sesión cambió/);assert.equal(a.calls.filter(x=>x==='commit').length,1)});
test('S2-C T11 no invitation, academic or Activity writes',async()=>{const a=setup();await a.createJointCPlan('alice','i_alice','catalog');assert.deepEqual(a.writes.map(w=>w.path),['jointPlans/'+P,...[1,2,3,4].map(n=>`jointPlans/${P}/slots/slot${n}`),'users/alice/jointPlanRefs/'+P])});
test('S2-C T12 selection never consulted',async()=>{const a=setup();Object.defineProperty(a.auth.currentUser,'activeCareerInstanceId',{get(){throw Error('selection accessed')}});assert.equal(await a.createJointCPlan('alice','explicit_instance','explicit_catalog'),P)});
test('S2-C T13 no reads or legacy fallback dependencies',async()=>{const a=setup();await a.createJointCPlan('alice','i_alice','catalog');assert.deepEqual(a.calls,['maintenance','batch','commit'])});
