const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const P='discoveryplan0001',Q='discoveryplan0002',stamp={seconds:1700000000,nanoseconds:0};
const plan=()=>({schemaVersion:3,origin:'native',ownerId:'other',ownerInstanceId:'i_other',catalogId:'catalog',closed:false,deleting:false,createdAt:stamp});
const ref=(id=P,data={schemaVersion:1,createdAt:stamp})=>({id,data:()=>data});
function setup(){
 const auth={currentUser:{uid:'alice'}},calls=[],records=new Map([[P,plan()],[Q,plan()]]),errors=new Map();let refs=[ref()],listError=null,hook=()=>{};
 const source=['src/jointPlanLogic.js','src/services/jointPlans.js'].map(p=>fs.readFileSync(path.resolve(__dirname,'..',p),'utf8').replace(/^import .*\r?\n/gm,'').replace(/export /g,'')).join('\n');
 const api=new Function('auth','db','collection','doc','getDocsFromServer','getDocFromServer',source+';return {discoverJointCPlans}')(auth,{},(_db,...p)=>p.join('/'),(_db,p)=>p,async p=>{calls.push(p);hook('list');if(listError)throw listError;return {docs:refs}},async p=>{calls.push(p);hook('get');const id=p.split('/')[1];if(errors.has(id))throw errors.get(id);return {exists:()=>records.has(id),data:()=>records.get(id)}});
 return {...api,auth,calls,records,errors,refs:r=>refs=r,onRead:f=>hook=f,listError:e=>listError=e};
}
test('S2-B T1 valid ref and C plan discovered',async()=>{const a=setup();assert.deepEqual(await a.discoverJointCPlans('alice'),{plans:[{planId:P,plan:plan()}],unavailable:[]})});
test('S2-B T2 multiple refs resolved individually',async()=>{const a=setup();a.refs([ref(P),ref(Q)]);assert.deepEqual((await a.discoverJointCPlans('alice')).plans.map(x=>x.planId),[P,Q]);assert.deepEqual(a.calls,['users/alice/jointPlanRefs','jointPlans/'+P,'jointPlans/'+Q])});
test('S2-B T3 missing plan is unavailable, never fabricated',async()=>{const a=setup();a.records.clear();assert.deepEqual(await a.discoverJointCPlans('alice'),{plans:[],unavailable:[{planId:P,reason:'unavailable'}]})});
test('S2-B T4 denied candidate yields no data or fallback',async()=>{const a=setup();a.errors.set(P,Object.assign(new Error('denied'),{code:'permission-denied'}));assert.deepEqual(await a.discoverJointCPlans('alice'),{plans:[],unavailable:[{planId:P,reason:'unavailable'}]});assert.equal(a.calls.length,2)});
test('S2-B T5 legacy/v2 plans never accepted as C',async()=>{for(const schemaVersion of [undefined,2]){const a=setup();a.records.set(P,{...plan(),schemaVersion});assert.deepEqual(await a.discoverJointCPlans('alice'),{plans:[],unavailable:[{planId:P,reason:'invalid-plan'}]})}});
test('S2-B T6 malformed C is explicitly reported',async()=>{const a=setup();a.records.set(P,{...plan(),ownerId:''});assert.equal((await a.discoverJointCPlans('alice')).unavailable[0].reason,'invalid-plan')});
test('S2-B T7 session required before any read',async()=>{for(const uid of ['alice','bob',undefined]){const a=setup();if(uid==='alice')a.auth.currentUser=null;await assert.rejects(a.discoverJointCPlans(uid));assert.equal(a.calls.length,0)}});
test('S2-B T8 session change after list or GET discards results',async()=>{for(const stage of ['list','get']){const a=setup();a.onRead(s=>{if(s===stage)a.auth.currentUser={uid:'alice'}});await assert.rejects(a.discoverJointCPlans('alice'),/sesión cambió/);assert.equal(a.calls.length,stage==='list'?1:2)}});
test('S2-B T9 selection is not consulted',async()=>{const a=setup();Object.defineProperty(a.auth.currentUser,'activeCareerInstanceId',{get(){throw Error('selection read')}});assert.equal((await a.discoverJointCPlans('alice')).plans.length,1)});
test('S2-B T10 mixed stale candidates do not trigger fallback',async()=>{const a=setup();a.refs([ref(P),ref(Q)]);a.records.delete(P);assert.deepEqual((await a.discoverJointCPlans('alice')).plans.map(p=>p.planId),[Q]);assert.equal(a.calls.length,3)});
test('S2-B T11 only private refs list and explicit parent GET',async()=>{const a=setup();await a.discoverJointCPlans('alice');assert.deepEqual(a.calls,['users/alice/jointPlanRefs','jointPlans/'+P])});
test('S2-B invalid ref schema, timestamp, extra fields or id never read parent',async()=>{for(const [id,data] of [[P,{schemaVersion:2,createdAt:stamp}],[P,{schemaVersion:1,createdAt:'today'}],[P,{schemaVersion:1,createdAt:stamp,member:true}],['../x',{schemaVersion:1,createdAt:stamp}]]){const a=setup();a.refs([ref(id,data)]);const r=await a.discoverJointCPlans('alice');assert.equal(r.plans.length,0);assert.equal(r.unavailable[0].reason,'invalid-ref');assert.equal(a.calls.length,1)}});
test('S2-B list/transport errors reject instead of returning empty',async()=>{for(const location of ['list','get']){const a=setup(),e=Object.assign(new Error('offline'),{code:'unavailable'});if(location==='list')a.listError(e);else a.errors.set(P,e);await assert.rejects(a.discoverJointCPlans('alice'),x=>x===e)}});
test('S2-B empty refs means no parent reads',async()=>{const a=setup();a.refs([]);assert.deepEqual(await a.discoverJointCPlans('alice'),{plans:[],unavailable:[]});assert.equal(a.calls.length,1)});
test('S2-B session replacement during denied GET is not hidden',async()=>{const a=setup();a.errors.set(P,Object.assign(new Error('denied'),{code:'permission-denied'}));a.onRead(stage=>{if(stage==='get')a.auth.currentUser=null});await assert.rejects(a.discoverJointCPlans('alice'),/sesión cambió/)});
