const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path')
const source=fs.readFileSync(path.resolve(__dirname,'../src/jointPlanLogic.js'),'utf8').replace(/export /g,'')
const a=new Function(source+';return {jointCInvitationOccurrencePath,decodeJointCInvitationOccurrence}')()
const P='explicitplan0001x',X='occurrence000001x',Y='occurrence000002y'
// Same six wire fields as the accepted C fixture; resolved server time for reads.
const fixture=()=>({slotId:'slot2',uid:'bob',invitedBy:'carol',cycle:'cycle00000000001',revision:3,createdAt:{seconds:1,nanoseconds:0}})
const decode=(d=fixture(),o=X)=>a.decodeJointCInvitationOccurrence(P,o,d)
test('O1 T1 explicit path',()=>assert.equal(a.jointCInvitationOccurrencePath(P,X),`jointPlans/${P}/invitationOccurrences/${X}`))
test('O1 T2 invalid plan IDs',()=>{for(const p of [null,'','short','x'.repeat(41),'a/b'])assert.throws(()=>a.jointCInvitationOccurrencePath(p,X))})
test('O1 T3 invalid occurrence IDs including import occupancy',()=>{for(const o of [null,'','short','x'.repeat(41),'import_'+X,'a/b'])assert.throws(()=>a.jointCInvitationOccurrencePath(P,o))})
test('O1 T4 valid occurrence decoded with exact wire payload',()=>assert.deepEqual(decode().occurrence,fixture()))
test('O1 T5 explicit identity retained in envelope',()=>{const d=decode();assert.equal(d.planId,P);assert.equal(d.occurrenceId,X)})
test('O1 T6 invitee is stored uid',()=>assert.equal(decode().occurrence.uid,'bob'))
test('O1 T7 slot retained',()=>assert.equal(decode().occurrence.slotId,'slot2'))
test('O1 T8 cycle retained',()=>assert.equal(decode().occurrence.cycle,'cycle00000000001'))
test('O1 T9 inviter independent of owner',()=>assert.equal(decode().occurrence.invitedBy,'carol'))
test('O1 T10 malformed values rejected',()=>{
  for(const d of [null,[],{}, {...fixture(),slotId:'slot5'},{...fixture(),uid:'a/b'},{...fixture(),invitedBy:null},{...fixture(),cycle:'short'},{...fixture(),revision:0},{...fixture(),revision:1.5},{...fixture(),revision:Number.MAX_SAFE_INTEGER+1},{...fixture(),createdAt:{seconds:1,nanoseconds:1e9}},{...fixture(),createdAt:'SERVER_TIMESTAMP'}])assert.throws(()=>decode(d))
})
test('O1 T11 each required field mandatory',()=>{for(const k of Object.keys(fixture())){const d=fixture();delete d[k];assert.throws(()=>decode(d))}})
test('O1 T12 redundant payload identity unsupported, never overrides path',()=>{for(const [k,v]of [['planId',P],['occurrenceId',Y],['inviteeUid','bob'],['schemaVersion',3],['status','pending']])assert.throws(()=>decode({...fixture(),[k]:v}))})
test('O1 T13 same invitee/slot X and Y retain distinct identities',()=>{assert.notEqual(decode().occurrenceId,decode(fixture(),Y).occurrenceId);assert.deepEqual(decode().occurrence,decode(fixture(),Y).occurrence)})
test('O1 T14 no authorization or external state inferred',()=>{const d=decode();assert.deepEqual(Object.keys(d),['planId','occurrenceId','occurrence']);for(const k of ['authorized','membership','sharing','activeCareerInstanceId','current'])assert.equal(k in d.occurrence,false)})
test('O1 T15 frozen input unchanged and timestamp detached',()=>{const d=fixture();Object.freeze(d.createdAt);Object.freeze(d);const out=decode(d);out.occurrence.createdAt.seconds=7;out.occurrence.uid='changed';assert.deepEqual(d,fixture())})
