export const subjects = [
  // CBC
  { code: 'ODO-CBC-QUI', name: 'Química', year: 1, level: 'CBC', term: 'CBC', hours: 68, prereqs: [] },
  { code: 'ODO-CBC-MAT', name: 'Matemática', year: 1, level: 'CBC', term: 'CBC', hours: 68, prereqs: [] },
  { code: 'ODO-CBC-FIS', name: 'Física e Introducción a la Biofísica', year: 1, level: 'CBC', term: 'CBC', hours: 68, prereqs: [] },
  { code: 'ODO-CBC-BIO', name: 'Biología e Introducción a la Biología Celular', year: 1, level: 'CBC', term: 'CBC', hours: 68, prereqs: [] },
  { code: 'ODO-CBC-IPC', name: 'Introducción al Pensamiento Científico', year: 1, level: 'CBC', term: 'CBC', hours: 68, prereqs: [] },
  { code: 'ODO-CBC-ICSE', name: 'Introducción al Conocimiento de la Sociedad y el Estado', year: 1, level: 'CBC', term: 'CBC', hours: 68, prereqs: [] },

  // 2° Año
  {
    code: 'N100',
    name: 'Inglés Técnico',
    year: 2,
    level: '2° Año',
    term: 'A/B',
    hours: 68,
    prereqs: ['ODO-CBC-QUI', 'ODO-CBC-MAT', 'ODO-CBC-FIS', 'ODO-CBC-BIO', 'ODO-CBC-IPC', 'ODO-CBC-ICSE'],
  },
  {
    code: 'N101',
    name: 'Anatomía General y Estomatológica',
    year: 2,
    level: '2° Año',
    term: 'Anual',
    hours: 68,
    prereqs: ['ODO-CBC-QUI', 'ODO-CBC-MAT', 'ODO-CBC-FIS', 'ODO-CBC-BIO', 'ODO-CBC-IPC', 'ODO-CBC-ICSE'],
  },
  {
    code: 'N102',
    name: 'Bioquímica General',
    year: 2,
    level: '2° Año',
    term: 'A',
    hours: 68,
    prereqs: ['ODO-CBC-QUI', 'ODO-CBC-MAT', 'ODO-CBC-FIS', 'ODO-CBC-BIO', 'ODO-CBC-IPC', 'ODO-CBC-ICSE'],
  },
  {
    code: 'N103',
    name: 'Histología y Embriología',
    year: 2,
    level: '2° Año',
    term: 'A',
    hours: 68,
    prereqs: ['ODO-CBC-QUI', 'ODO-CBC-MAT', 'ODO-CBC-FIS', 'ODO-CBC-BIO', 'ODO-CBC-IPC', 'ODO-CBC-ICSE'],
  },
  {
    code: 'N105',
    name: 'Inmunología y Microbiología I',
    year: 2,
    level: '2° Año',
    term: 'B',
    hours: 68,
    prereqs: ['N102', 'N103'],
  },
  {
    code: 'N106',
    name: 'Biología Bucal',
    year: 2,
    level: '2° Año',
    term: 'B',
    hours: 68,
    prereqs: ['N102', 'N103'],
  },
  {
    code: 'N108',
    name: 'Biofísica Aplicada a la Práctica Odontológica',
    year: 2,
    level: '2° Año',
    term: 'B',
    hours: 68,
    prereqs: ['N102'],
  },
  {
    code: 'N110',
    name: 'Inserción Temprana en la Clínica',
    year: 2,
    level: '2° Año',
    term: 'B',
    hours: 68,
    prereqs: ['ODO-CBC-QUI', 'ODO-CBC-MAT', 'ODO-CBC-FIS', 'ODO-CBC-BIO', 'ODO-CBC-IPC', 'ODO-CBC-ICSE'],
  },
  {
    code: 'N111',
    name: 'Diagnóstico por Imágenes con Radiofísica Sanitaria',
    year: 2,
    level: '2° Año',
    term: 'B',
    hours: 68,
    prereqs: ['N103'],
  },

    // 3° Año
  {
    code: 'N201',
    name: 'Fisiología',
    year: 3,
    level: '3° Año',
    term: 'Anual',
    hours: 68,
    prereqs: ['N106', 'N108'],
  },
  {
    code: 'N202',
    name: 'Patología General',
    year: 3,
    level: '3° Año',
    term: 'A',
    hours: 68,
    prereqs: ['N105', 'N106'],
  },
  {
    code: 'N203',
    name: 'Materiales Dentales I',
    year: 3,
    level: '3° Año',
    term: 'A',
    hours: 68,
    prereqs: ['N108'],
  },
  {
    code: 'N204',
    name: 'Preclínica de Odontología Restauradora I',
    year: 3,
    level: '3° Año',
    term: 'A',
    hours: 68,
    prereqs: ['N101', 'N110', 'N106'],
  },
  {
    code: 'N206',
    name: 'Odontología Preventiva y Mínimamente Invasiva I',
    year: 3,
    level: '3° Año',
    term: 'A',
    hours: 68,
    prereqs: ['N101', 'N105', 'N106', 'N110', 'N111'],
  },
  {
    code: 'N211',
    name: 'Preclínica Quirúrgica y Anestesia',
    year: 3,
    level: '3° Año',
    term: 'A',
    hours: 68,
    prereqs: ['N101', 'N110', 'N105'],
  },
  {
    code: 'N205',
    name: 'Microbiología II',
    year: 3,
    level: '3° Año',
    term: 'A',
    hours: 68,
    prereqs: ['N105'],
  },
  {
    code: 'N207',
    name: 'Odontología Preventiva y Mínimamente Invasiva II',
    year: 3,
    level: '3° Año',
    term: 'B',
    hours: 68,
    prereqs: ['N204', 'N206', 'N211'],
  },
  {
    code: 'N208',
    name: 'Preclínica de Odontología Restauradora II',
    year: 3,
    level: '3° Año',
    term: 'B',
    hours: 68,
    prereqs: ['N203', 'N204', 'N206'],
  },
  {
    code: 'N209',
    name: 'Endodoncia I',
    year: 3,
    level: '3° Año',
    term: 'B',
    hours: 68,
    prereqs: ['N204', 'N206', 'N211'],
  },
  {
    code: 'N210',
    name: 'Patología Bucal',
    year: 3,
    level: '3° Año',
    term: 'B',
    hours: 68,
    prereqs: ['N202'],
  },
  {
    code: 'N212',
    name: 'Materiales Dentales II',
    year: 3,
    level: '3° Año',
    term: 'B',
    hours: 68,
    prereqs: ['N203'],
  },
  {
    code: 'N213',
    name: 'Bioética y Ejercicio Profesional',
    year: 3,
    level: '3° Año',
    term: 'B',
    hours: 68,
    prereqs: ['N110'],
  },
  {
    code: 'N214',
    name: 'Introducción a la Periodoncia',
    year: 3,
    level: '3° Año',
    term: 'B',
    hours: 68,
    prereqs: ['N206'],
  },

    // 4° Año
  {
    code: 'N302',
    name: 'Preclínica de Rehabilitación Protética',
    year: 4,
    level: '4° Año',
    term: 'Anual',
    hours: 68,
    prereqs: ['N208', 'N212'],
  },
  {
    code: 'N303',
    name: 'Farmacología',
    year: 4,
    level: '4° Año',
    term: 'Anual',
    hours: 68,
    prereqs: ['N201', 'N202'],
  },
  {
    code: 'N304',
    name: 'Medicina Interna en la Práctica Odontológica',
    year: 4,
    level: '4° Año',
    term: 'Anual',
    hours: 68,
    prereqs: ['N201', 'N210', 'N110'],
  },
  {
    code: 'N308',
    name: 'Endodoncia II',
    year: 4,
    level: '4° Año',
    term: 'Anual',
    hours: 68,
    prereqs: ['N205', 'N210', 'N208', 'N209', 'N207'],
  },
  {
    code: 'N309',
    name: 'Periodoncia',
    year: 4,
    level: '4° Año',
    term: 'Anual',
    hours: 68,
    prereqs: ['N205', 'N210', 'N207', 'N214'],
  },
  {
    code: 'N310',
    name: 'Odontología Restauradora',
    year: 4,
    level: '4° Año',
    term: 'Anual',
    hours: 68,
    prereqs: ['N207', 'N208', 'N212'],
  },
  {
    code: 'N306',
    name: 'Bioestadística y Metodología de la Investigación',
    year: 4,
    level: '4° Año',
    term: 'A',
    hours: 68,
    prereqs: ['N100'],
  },
  {
    code: 'N305',
    name: 'Historia de la Odontología',
    year: 4,
    level: '4° Año',
    term: 'A/B',
    hours: 68,
    prereqs: [
      'ODO-CBC-QUI',
      'ODO-CBC-MAT',
      'ODO-CBC-FIS',
      'ODO-CBC-BIO',
      'ODO-CBC-IPC',
      'ODO-CBC-ICSE',
    ],
  },
  {
    code: 'N311',
    name: 'Cirugía y Traumatología Bucomaxilofacial I',
    year: 4,
    level: '4° Año',
    term: 'Anual',
    hours: 68,
    prereqs: ['N205', 'N207', 'N210', 'N211', 'N201'],
  },

    // 5° Año
  {
    code: 'N401',
    name: 'Odontología Rehabilitadora Integral',
    year: 5,
    level: '5° Año',
    term: 'Anual',
    hours: 68,
    prereqs: ['N302', 'N308', 'N309', 'N310'],
  },
  {
    code: 'N402',
    name: 'Cirugía y Traumatología Bucomáxilofacial II',
    year: 5,
    level: '5° Año',
    term: 'Anual',
    hours: 68,
    prereqs: ['N303', 'N304', 'N311'],
  },
  {
    code: 'N403',
    name: 'Odontología Integral de Niños y Adolescentes',
    year: 5,
    level: '5° Año',
    term: 'Anual',
    hours: 68,
    prereqs: ['N303', 'N304', 'N308', 'N309', 'N310', 'N311'],
  },
  {
    code: 'N405',
    name: 'Materiales Dentales III',
    year: 5,
    level: '5° Año',
    term: 'A',
    hours: 68,
    prereqs: ['N302', 'N310'],
  },
  {
    code: 'N407',
    name: 'Diagnóstico por Imágenes II',
    year: 5,
    level: '5° Año',
    term: 'A',
    hours: 68,
    prereqs: ['N311'],
  },
  {
    code: 'N404',
    name: 'Medicina Bucal I',
    year: 5,
    level: '5° Año',
    term: 'B',
    hours: 68,
    prereqs: ['N304', 'N303'],
  },
  {
    code: 'N409',
    name: 'Epidemiología y Salud de las Poblaciones',
    year: 5,
    level: '5° Año',
    term: 'B',
    hours: 68,
    prereqs: ['N207', 'N306'],
  },

    // 6° Año
  {
    code: 'N501',
    name: 'Odontología Integral Adultos (PPS)',
    year: 6,
    level: '6° Año',
    term: 'Anual',
    hours: 68,
    prereqs: ['N401', 'N402', 'N404', 'N405'],
  },
  {
    code: 'N502',
    name: 'Cirugía y Traumatología Bucomaxilofacial III',
    year: 6,
    level: '6° Año',
    term: 'Anual',
    hours: 68,
    prereqs: ['N402', 'N404'],
  },
  {
    code: 'N503',
    name: 'Articulación Docencia-Servicios-Investigación (Práctica Social Educativa)',
    year: 6,
    level: '6° Año',
    term: 'Anual',
    hours: 68,
    prereqs: ['N403', 'N409'],
  },
  {
    code: 'N509',
    name: 'Odontología Integral para el Adulto Mayor',
    year: 6,
    level: '6° Año',
    term: 'Anual',
    hours: 68,
    prereqs: ['N401', 'N404'],
  },
  {
    code: 'N506',
    name: 'Ortodoncia I',
    year: 6,
    level: '6° Año',
    term: 'A',
    hours: 68,
    prereqs: ['N403', 'N407'],
  },
  {
    code: 'N504',
    name: 'Medicina Bucal II',
    year: 6,
    level: '6° Año',
    term: 'A',
    hours: 68,
    prereqs: ['N404'],
  },
  {
    code: 'N507',
    name: 'Odontología Forense',
    year: 6,
    level: '6° Año',
    term: 'A',
    hours: 68,
    prereqs: ['N213', 'N401'],
  },
  {
    code: 'N508',
    name: 'Sistema de Salud y Gestión Clínica',
    year: 6,
    level: '6° Año',
    term: 'B',
    hours: 68,
    prereqs: ['N409', 'N507'],
  },

  // Módulos Asistenciales Orientados (Electivos)
  {
    code: 'N601',
    name: 'Riesgo Sistémico de la Patología Buco-dental',
    year: 6,
    level: 'Módulos Electivos',
    term: 'Electiva',
    hours: 68,
    prereqs: ['N304'],
  },
  {
    code: 'N602',
    name: 'Atención Odontológica en Pacientes con Discapacidad',
    year: 6,
    level: 'Módulos Electivos',
    term: 'Electiva',
    hours: 68,
    prereqs: ['N304'],
  },
  {
    code: 'N603',
    name: 'Ortodoncia II',
    year: 6,
    level: 'Módulos Electivos',
    term: 'Electiva',
    hours: 68,
    prereqs: ['N506'],
  },
  {
    code: 'N604',
    name: 'Programa Rural de Atención Odontológica',
    year: 6,
    level: 'Módulos Electivos',
    term: 'Electiva',
    hours: 68,
    prereqs: ['N409', 'N403'],
  },
  {
    code: 'N605',
    name: 'Traumatismos Dentarios',
    year: 6,
    level: 'Módulos Electivos',
    term: 'Electiva',
    hours: 68,
    prereqs: ['N308', 'N309', 'N402'],
  },
  {
    code: 'N606',
    name: 'Tomografía Computada en la Práctica Clínica Odontológica',
    year: 6,
    level: 'Módulos Electivos',
    term: 'Electiva',
    hours: 68,
    prereqs: ['N407'],
  },
  {
    code: 'N607',
    name: 'Atención Integral de Pacientes con Sequedad Bucal',
    year: 6,
    level: 'Módulos Electivos',
    term: 'Electiva',
    hours: 68,
    prereqs: ['N404'],
  },
  {
    code: 'N608',
    name: 'Módulo Asistencial Integrado de Baja Complejidad',
    year: 6,
    level: 'Módulos Electivos',
    term: 'Electiva',
    hours: 68,
    prereqs: ['N308', 'N310'],
  },
  {
    code: 'N609',
    name: 'Nuevas Tecnologías en Odontología Rehabilitadora',
    year: 6,
    level: 'Módulos Electivos',
    term: 'Electiva',
    hours: 68,
    prereqs: ['N302', 'N407'],
  },
  {
    code: 'N610',
    name: 'Módulo Asistencial de Urgencias Odontológicas',
    year: 6,
    level: 'Módulos Electivos',
    term: 'Electiva',
    hours: 68,
    prereqs: ['N304', 'N308'],
  },
]

export const initialStatus = Object.fromEntries(
  subjects.map((subject) => [subject.code, 'Pendiente'])
)