// Real product Rules + real product service. Admin seeds only test preconditions.
const {test}=require('node:test'),assert=require('node:assert/strict'),sdk=require('firebase/firestore')
const h=require('./helpers.cjs'),{load,fixture,P,X,Y,C,C2,root,time}=require('../joint-c-invite-harness.cjs')
test('E1 product NEW/REINVITE and private ref contract',async t=>{
 const e=await h.initialize(),clients=new Map(),REF=`users/bob/jointPlanRefs/${P}`
 const db=u=>{if(!clients.has(u))clients.set(u,e.authenticatedContext(u,h.claims(u)).firestore());return clients.get(u)}
 const stamp=sdk.Timestamp.fromMillis(time.seconds*1000)
 const firestoreValues=v=>{if(v&&typeof v==='object'){if(Object.keys(v).sort().join(',')==='nanoseconds,seconds')return new sdk.Timestamp(v.seconds,v.nanoseconds);return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,Array.isArray(x)?x.map(firestoreValues):firestoreValues(x)]))}return v}
 async function reset(){await e.clearFirestore();await h.seed(e,firestoreValues(fixture()))}
 async function read(p){let d;await e.withSecurityRulesDisabled(async c=>d=(await sdk.getDoc(sdk.doc(c.firestore(),p))).data());return d}
 const api=(uid='alice',mutate=null)=>load(mutate?{...sdk,runTransaction:(database,fn)=>sdk.runTransaction(database,tx=>fn({get:r=>tx.get(r),update:(...a)=>tx.update(...a),set:(ref,data,options)=>{const change=mutate(ref,data,options);return change.options?tx.set(ref,change.data,change.options):tx.set(ref,change.data)}}))}:sdk,{currentUser:{uid}},db(uid))
 const invite=(over={},client=api())=>{const a={uid:'alice',slot:'slot1',u:'bob',o:X,c:C,rev:0,prev:null,...over};return client.inviteJointCParticipant(a.uid,P,a.slot,a.u,a.o,a.c,a.rev,a.prev)}
 async function release(){const d=db('bob'),b=sdk.writeBatch(d),s=await read(root+'/slots/slot1');b.set(sdk.doc(d,root,'slots','slot1'),{status:'empty',uid:null,revision:s.revision+1,occurrence:null,cycle:null,invitedBy:null,binding:null,joinedOccurrence:null,updatedAt:sdk.serverTimestamp()});b.delete(sdk.doc(d,root,'inviteeIndex','bob'));await b.commit()}
 async function denied(fn){let error;try{await fn()}catch(x){error=x}assert.ok(error);t.diagnostic(JSON.stringify({code:error.code,message:error.message}));assert.equal(error.code,'permission-denied');assert.ok(!/1000\s+expressions|service[ -]call error|resource[ -]exhaust|maximum[^\n]*calls/i.test(error.message),'Resource exhaustion is not logical denial')}
 async function gate(label,fn){await t.test(label,fn);if(t.signal.aborted)throw Error('aborted')}
 try{
  await gate('FIRST NEW real service five documents',async()=>{await reset();await invite();assert.deepEqual(await read(REF),{schemaVersion:1});assert.equal((await read(root+'/slots/slot1')).uid,'bob');assert.equal((await read(root+'/inviteeIndex/bob')).slotId,'slot1');assert.equal((await read(root+'/invitationOccurrences/'+X)).cycle,C);assert.equal((await read(`users/bob/activityInbox/sp_${P}_${X}`)).schemaVersion,3)})
  for(const historical of [false,true])await gate('NEW after RELEASE '+(historical?'historical':'minimal'),async()=>{await reset();await invite();await release();if(historical)await h.seed(e,{[REF]:{schemaVersion:1,createdAt:stamp}});const before=await read(REF),old=await read(root+'/invitationOccurrences/'+X),notice=await read(`users/bob/activityInbox/sp_${P}_${X}`);await invite({o:Y,rev:2});assert.deepEqual(await read(REF),before);assert.deepEqual(await read(root+'/invitationOccurrences/'+X),old);assert.deepEqual(await read(`users/bob/activityInbox/sp_${P}_${X}`),notice)})
  await gate('pending REINVITE three writes',async()=>{await reset();await invite();await h.seed(e,{'friendships/alice:bob':{...await read('friendships/alice:bob'),cycleId:C2}});const before=await read(REF),old=await read(root+'/invitationOccurrences/'+X);await invite({o:Y,c:C2,rev:1,prev:X});assert.equal((await read(root+'/slots/slot1')).occurrence,Y);assert.deepEqual(await read(REF),before);assert.deepEqual(await read(root+'/invitationOccurrences/'+X),old)})
  await gate('invitedBy != owner service reads only own binding',async()=>{await reset();await h.seed(e,{[root+'/slots/slot2']:{...await read(root+'/slots/slot2'),status:'member',uid:'carol',revision:1,occurrence:Y,cycle:C,invitedBy:'alice',binding:'i_carol',joinedOccurrence:Y},[root+'/inviteeIndex/carol']:{slotId:'slot2'},'friendships/bob:carol':{participants:['bob','carol'],senderId:'bob',recipientId:'carol',status:'accepted',cycleId:C}});await invite({uid:'carol'},api('carol'));assert.equal((await read(root+'/slots/slot1')).invitedBy,'carol')})
  await gate('foreign GET/LIST denied; own minimal list valid',async()=>{await reset();await invite();await denied(()=>sdk.getDoc(sdk.doc(db('alice'),REF)));await denied(()=>sdk.getDocs(sdk.collection(db('alice'),'users/bob/jointPlanRefs')));assert.equal((await sdk.getDocs(sdk.collection(db('bob'),'users/bob/jointPlanRefs'))).size,1)})
  await gate('standalone create/no-op/update/delete denied',async()=>{await reset();await denied(()=>sdk.setDoc(sdk.doc(db('alice'),REF),{schemaVersion:1},{merge:true}));await invite();await denied(()=>sdk.setDoc(sdk.doc(db('alice'),REF),{schemaVersion:1},{merge:true}));await denied(()=>sdk.updateDoc(sdk.doc(db('bob'),REF),{extra:true}));await denied(()=>sdk.deleteDoc(sdk.doc(db('bob'),REF)))})
  for(const mutation of ['schema','timestamp','extra','removeTimestamp'])await gate('atomic ref mutation denied '+mutation,async()=>{await reset();await h.seed(e,{[REF]:{schemaVersion:1,createdAt:stamp}});const before=await read(REF);const client=api('alice',(ref,data,options)=>ref.path!==REF?{data,options}:{data:mutation==='schema'?{schemaVersion:2}:mutation==='timestamp'?{schemaVersion:1,createdAt:sdk.serverTimestamp()}:mutation==='extra'?{schemaVersion:1,extra:true}:{schemaVersion:1},options:mutation==='removeTimestamp'?undefined:{merge:true}});await denied(()=>invite({},client));assert.deepEqual(await read(REF),before);assert.equal((await read(root+'/slots/slot1')).status,'empty');assert.equal(await read(root+'/inviteeIndex/bob'),undefined);assert.equal(await read(root+'/invitationOccurrences/'+X),undefined);assert.equal(await read(`users/bob/activityInbox/sp_${P}_${X}`),undefined)})
  await gate('omitted Activity denies whole service transaction',async()=>{await reset();const wrapped={...sdk,runTransaction:(database,fn)=>sdk.runTransaction(database,tx=>fn({get:r=>tx.get(r),update:(...a)=>tx.update(...a),set:(r,d,o)=>{if(!r.path.includes('/activityInbox/'))return o?tx.set(r,d,o):tx.set(r,d)}}))};await denied(()=>invite({},load(wrapped,{currentUser:{uid:'alice'}},db('alice'))));assert.equal((await read(root+'/slots/slot1')).status,'empty');assert.equal(await read(REF),undefined);assert.equal(await read(root+'/invitationOccurrences/'+X),undefined)})
  await gate('stale cycle/revision/occurrence and duplicate UID rejected by service',async()=>{await reset();await assert.rejects(invite({c:C2}));await assert.rejects(invite({rev:1}));await assert.rejects(invite({prev:Y}));await assert.rejects(invite({slot:'slot5'}));await invite();await assert.rejects(invite({slot:'slot2',o:Y}));assert.equal((await read(root+'/slots/slot2')).status,'empty')})
  for(const scenario of ['sameUid','sameSlot','reinvite'])await gate('concurrency '+scenario,async()=>{await reset();let a={},b={slot:'slot2',o:Y};if(scenario==='sameSlot')b={u:'dave',o:Y};if(scenario==='reinvite'){await invite();await h.seed(e,{'friendships/alice:bob':{...await read('friendships/alice:bob'),cycleId:C2}});a={o:Y,c:C2,rev:1,prev:X};b={...a,o:'occurrence000003z'}}const result=await Promise.allSettled([invite(a),invite(b)]);assert.equal(result.filter(x=>x.status==='fulfilled').length,1);const occupants=[];for(let n=1;n<=4;n++){const slot=await read(root+'/slots/slot'+n);if(slot.uid){occupants.push(slot.uid);assert.deepEqual(await read(root+'/inviteeIndex/'+slot.uid),{slotId:'slot'+n});assert.ok(await read(root+'/invitationOccurrences/'+slot.occurrence));assert.ok(await read('users/'+slot.uid+'/activityInbox/sp_'+P+'_'+slot.occurrence));assert.ok(await read('users/'+slot.uid+'/jointPlanRefs/'+P))}}assert.equal(occupants.length,1)})
 }finally{await e.cleanup()}
})
